chore(bin): bin script housekeeping

diff --git a/bin/archive b/bin/archive
--- a/bin/archive
+++ b/bin/archive
@@ -1,24 +1,22 @@
 #!/usr/bin/env zsh
 
-set -euo pipefail
+set -Eeuo pipefail
 
-# why this isn't pulled out of fpath defined in .zshenv, I don't know.
-slugify() {
-  echo "$1" | iconv -t ascii//TRANSLIT | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr "[:upper:]" "[:lower:]"
-}
+# Load slugify from zshfunctions
+fpath=(~/.dotfiles/zshfunctions $fpath)
+autoload -Uz slugify
 
-UNAME=$(uname -o)
-if [[ ${UNAME} == Darwin ]]; then
-  TAR=$(whence -p gtar)
-  if [[ -z ${TAR} ]]; then
-    echo "tar not found, please exceute 'brew install gnu-tar'"
+# We want gtar because tar on macOS doesn't support the --exclude-vcs-ignores option
+if [[ "${OSTYPE}" == darwin* ]]; then
+  (( ! $+commands[gtar] )) && {
+    echo "tar not found, please execute 'brew install gnu-tar'"
     exit 1
-  fi
+  }
 else
-  TAR=$(whence -p tar)
+  TAR=${commands[tar]:-/usr/bin/tar}
 fi
 
-BACKUP_DIR="${HOME}/project/archives"
+BACKUP_DIR="${HOME}/projects/archives"
 DIR="${1}"
 
 [[ ${DIR} ]] || {
diff --git a/bin/flac2mp3 b/bin/flac2mp3
--- a/bin/flac2mp3
+++ b/bin/flac2mp3
@@ -1,4 +1,11 @@
-#!/bin/sh
+#!/usr/bin/env zsh
+
+set -Eeuo pipefail
+
+if (( ! $+commands[ffmpeg] )); then
+  echo "ffmpeg not found"
+  exit 1
+fi
 
 FILE=$1
 ffmpeg -i "${FILE}" -b:a 256k -map_metadata 0 -id3v2_version 3 "${FILE%.flac}.mp3"
diff --git a/tag-osx/bin/imgls b/tag-osx/bin/imgls
--- a/tag-osx/bin/imgls
+++ b/tag-osx/bin/imgls
@@ -2,43 +2,43 @@
 # tmux requires unrecognized OSC sequences to be wrapped with DCS tmux;
 # <sequence> ST, and for all ESCs in <sequence> to be replaced with ESC ESC. It
 # only accepts ESC backslash for ST.
-function print_osc() {
-    if [ x"$TERM" = "xscreen" ] ; then
+function print_osc {
+    if [ "$TERM" = "xscreen" ] ; then
         printf "\033Ptmux;\033\033]"
     else
         printf "\033]"
     fi
 }
 
-function check_dependency() {
+function check_dependency {
   if ! (builtin command -V "$1" > /dev/null 2>& 1); then
-    echo "imgcat: missing dependency: can't find $1" 1>& 2
+    echo "imgls: missing dependency: can't find $1" 1>& 2
     exit 1
   fi
 }
 
 # More of the tmux workaround described above.
-function print_st() {
-    if [ x"$TERM" = "xscreen" ] ; then
+function print_st {
+    if [ "$TERM" = "xscreen" ] ; then
         printf "\a\033\\"
     else
         printf "\a"
     fi
 }
 
-function list_file() {
+function list_file {
   fn=$1
-  dims=$(php -r 'if (!is_file($argv[1])) exit(1); $a = getimagesize($argv[1]); if ($a==FALSE) exit(1); else { echo $a[0] . "x" .$a[1]; exit(0); }' "$fn")
+  dims=$(identify -format "%wx%h" "$fn" 2>/dev/null)
   rc=$?
   if [[ $rc == 0 ]] ; then
     print_osc
-    printf '1337;File=name='`echo -n "$fn" | base64`";"
+    printf '1337;File=name=%s;' "$(echo -n "$fn" | base64)"
     wc -c "$fn" | awk '{printf "size=%d",$1}'
     printf ";inline=1;height=3;width=3;preserveAspectRatio=true"
     printf ":"
     base64 < "$fn"
     print_st
-    if [ x"$TERM" == "xscreen" ] ; then
+    if [ "$TERM" == "xscreen" ] ; then
       # This works in plain-old tmux but does the wrong thing in iTerm2's tmux
       # integration mode. tmux doesn't know that the cursor moves when the
       # image code is sent, while iTerm2 does. I had to pick one, since
@@ -61,7 +61,7 @@ function list_file() {
   fi
 }
 
-check_dependency php
+check_dependency identify
 check_dependency base64
 check_dependency wc
 
